name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Build
      run: go build -v .
    
    - name: Test
      run: go test -v ./...
    
    - name: Test cross-compilation
      run: |
        GOOS=linux GOARCH=amd64 go build -v .
        GOOS=darwin GOARCH=amd64 go build -v .
        GOOS=windows GOARCH=amd64 go build -v .